### ISSUE TITLE
Add Node.js implementation

### ISSUE THREAD

**Issue by John-Lin** [John-Lin/wallofsheep#2]
OSX can play with it. 
@lockys You can test it on you local laptop need fond-end support! :+1:

**Comment by lockys** [comment]
:+1: OK, I' ll try to play around that. :smile:

**Comment by wirelessice** [comment]
'run node sniffer.js -i eth0' 

module.js:328
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/iccecolor/wisec/wallofsheep/nodejs/sniffer.js:7:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

  why？

**Comment by LeonardoW9** [comment]
What version of node is this as I've tried running to no avail...

**Comment by John-Lin** [comment]
@LeonardoW9  Sorry, this repo is no longer maintained
